### ISSUE TITLE
Requires `libxenstore.so` symlink to be present

### ISSUE THREAD

**Issue by ydirson** [Wenzel/xenstore#16]
Executables built with these bindings depend on the `libxenstore.so` symlink typically shipped as part of dev packages (`libxen-dev`  in Debian, which pulls tons of unneeded stuff for this lib's purpose).

We should arrange to get the SONAME for the lib, and use that instead, so binaries can rely only on libxenstore runtime.

**Comment by Wenzel** [comment]
I agree that end-user binaries depending on pulling dev packages is not the way to go.

Can you detail how these changes might be implemented ?
I assume that we will rely on [`libloading`](https://crates.io/crates/libloading) as well ?

**Comment by ydirson** [comment]
I think it could boil down to (a portable equivalent of) reading the `libxenstore.so` ELF header to get the `SONAME` at build time. But since, portability-wise, `libxenstore` only seems to apply to Unix-like systems (there's a wholly different API on Windows), maybe a `readlink("libxenstore.so")` would be sufficient.
I'm baffled by `libloading` documentation not even mentioning the problem, there must be some good-practice documented somewhere.

(stepping back, this issue probably rather belongs to the `xenstore` crate itself)
