### ISSUE TITLE
`enum-primitive-derive` pulls old `syn` v1

### ISSUE THREAD

**Issue by ydirson** [Wenzel/xenstore#18]
`enum-primitive-derive` seems unmaintained and pulls old likely-unmaintained `syn v1` (no release in 2y, see https://gitlab.com/cardoe/enum-primitive-derive/-/issues/10)

A quick check in https://gist.github.com/stonegao/39ce1362c561d28c253dbfa7772db40d could hint that `derive_builder` or `strum` could provide a replacement ? (disclaimer: did not check any further than their last release date)

**Comment by Wenzel** [comment]
closed by #20
